### ISSUE TITLE
Kabanero 0.2.0. Documentation about tekton

### ISSUE THREAD

**Issue by jxadro** [kabanero-io/docs#179] opened 2019-11-04 20:42 UTC
It would be good to have some article in "kabanero.io" that puts some glue between appsody stacks and tekton pipelines.

I think the only documentation / guide available about tekton in kabanero.io is how to create a webhook.

**Comment by bschrammIBM** [comment] 2019-11-04 22:59
@jxadro Please see the guide that is pending final review at: https://github.com/kabanero-io/draft-guide-working-with-pipelines/blob/master/pipelines.adoc.

**Comment by bschrammIBM** [comment] 2019-11-04 23:02
I think this may be a duplicate of https://github.com/kabanero-io/docs/issues/56

**Comment by stephenkinder** [comment] 2019-11-07 22:00
@jxadro does the guide Barbara pointed out address your concern?

**Comment by mingcyu** [comment] 2020-01-09 16:24
Close due to inactivity and assume that the link mentioned above satisfies the issue

**Closed by mingcyu** 2020-01-09 16:24 UTC
Labels: documentation
