### ISSUE TITLE
Write a guide for "Using kAppNav" the application navigator

### ISSUE THREAD

**Issue by bschrammIBM** [kabanero-io/docs#57] opened 2019-08-27 00:18 UTC
The kAppNav tool is part of the kabanero release.
It is the open source version of Application Navigator https://www.ibm.com/support/knowledgecenter/en/SS7K4U_9.0.5/com.ibm.websphere.zseries.doc/ae/ccld_appnav.html
The engineering contact is: Chris Vignola 
See https://github.com/kappnav/README

**Comment by marikaj123** [comment] 2019-10-04 19:22
Need kAppVav team to help with this.

**Comment by bschrammIBM** [comment] 2019-10-04 23:51
Title could be: `How to manage microservice-based apps using kAppNav`

**Comment by marikaj123** [comment] 2019-10-15 23:27
According to Richard and Chris V, the issue will be completed by this Friday.

**Comment by marikaj123** [comment] 2019-10-17 03:30
According to Chris, the team is looking to out the appnav guide on kabanero.io

**Comment by bschrammIBM** [comment] 2019-10-17 18:21
Dolores Lopez has source material for the kAppNav guide, according to slack message:

```Dolores Lopez:2 hours ago
Hello, I am looking for information on how to add kAppNav documentation in Kabanero.io.
1)    Are there any guidelines/procedures we need to follow to format and submit docs
2)    Who needs to review/approve them
3)    What are the datelines to submit doc to be included in Kabanero operator 0.2.0```

+1-512-286-7283 (Office)
doloresl@us.ibm.com
Dolores Lopez/Austin/IBM

**Comment by marikaj123** [comment] 2019-10-17 18:31
@bschrammIBM - Would we consider this issue as a duplicate of introduce KnappNav in kabanero.io #231? If, yes, can it be closed?

**Comment by alohr51** [comment] 2019-10-17 19:16
@marikaj123 kabanero-io/kabanero-website/issues/231 is about adding a mention of kAppNav to the website pages itself, this one is writing a **guide** for kAppNav that would also go on the website so I wouldn't consider them duplicates.

**Comment by cvignola** [comment] 2019-10-18 04:22
@Rwalls1 Draft here:  https://ibm.box.com/s/berqr4swcnm3m56kuzigf32a6k8fu2y4

**Comment by Rwalls1** [comment] 2019-10-18 20:38
@cvignola @ralanlittle @nateziemann Guide at https://github.com/kabanero-io/draft-guide-using-kAppNav is ready for review.

**Comment by Rwalls1** [comment] 2019-10-24 19:55
@ralanlittle @nateziemann Please review: https://github.com/kabanero-io/draft-guide-using-kAppNav

**Comment by mingcyu** [comment] 2019-12-02 15:04
Live on Kabanero site. Closing this issue

**Closed by mingcyu** 2019-12-02 15:04 UTC
Labels: ID-reviewed, documentation, guide, release-0.2
