### ISSUE TITLE
Write a Guide for "Working with Pipelines"

### ISSUE THREAD

**Issue by bschrammIBM** [kabanero-io/docs#56] opened 2019-08-25 19:31 UTC
corresponds to

**Comment by bschrammIBM** [comment] 2019-10-04 23:49
Might make sense to include the troubleshooting information in https://github.com/kabanero-io/docs/issues/116 in the Pipelines Guide.

**Comment by mingcyu** [comment] 2019-10-07 14:11
Need to check with Barbara if this covers issues #78 and #79 of Doc Repo

**Comment by SueChaplain** [comment] 2019-10-09 08:45
>Need to check with Barbara if this covers issues #78 and #79 of Doc Repo

I believe @mingcyu is referring to the issues in the pipelines repo, which have been raised by SVT (@mtamboli) 

- https://github.com/kabanero-io/kabanero-pipelines/issues/78
- https://github.com/kabanero-io/kabanero-pipelines/issues/79

@marikaj123 @bschrammIBM - we need some better coordination between issues that the SVT team are raising that are duplicating plans for other guides and documentation.

**Comment by kvijai82** [comment] 2019-10-09 12:21
We have a lot of issues floating around pipeline docs :) I am hoping this consolidated version addresses all of it.  This is my first draft of it.  Still have a few more additions and updates I would like to get in today.  

Would appreciate any initial feedback on this.  @bschrammIBM @mtamboli @aadeshpa @smcclem @tseelbach @stephenkinder 

# Kabanero Pipelines

# Introduction

Kabanero leverage Tekton pipelines to illustrate a CI/CD work flows.  Each of the featured Kabanero collections contain a default pipeline that will build the collection, publish the image to a docker repo, and then deploy the image to the k8s cluster to illustrate an end to end flow.  You can add additional tasks and pipelines to the collections.  All the tasks and pipelines will be activated by Kabanero operator.

To learn more about Tekton Pipelines and creating new tasks, please review these resources:
https://github.com/tektoncd/pipeline/tree/master/docs#usage https://github.com/tektoncd/pipeline/blob/master/docs/tutorial.md

# Tasks and Pipelines

The Kabanero Collections contain the tasks & pipelines associated with the collection under <collection-name>/pipelines once the collection is built.

Note: The featured collections share the same tasks & pipelines and the collections build will copy the files from https://github.com/kabanero-io/collections/tree/master/incubator/common/pipelines/default to <collection-name>/pipelines during build.

Build-deploy-pipeline.yaml (https://github.com/kabanero-io/collections/blob/master/incubator/common/pipelines/default/build-deploy-pipeline.yaml) is the primary pipeline associated with the collections that will build, publish the container image, and deploy the application.  It looks for git-source and docker-image resources that will be used by the build-task and deploy-task.

Build-task.yaml builds a container image from the artifacts in the git-source repository.  Once the image is built, it will publish it to the docker-image URL.

Deploy-task.yaml will modify the app-deploy.yaml, which describes the deployment options for the application, to point to the image that was published and will deploy the application using the appsody operator.

# Running the pipelines

## Prereqs

You have the Kabanero foundation installed on Red Hat Origin Community Distribution of Kubernetes (OKD) or OpenShift Container Platform (OCP) cluster.  It has the necessary Kabanero, Isito, Knative, and Tekton components installed.  Please refer to https://github.com/kabanero-io/kabanero-foundation for more details on installing the Kabanero foundation.

Identify the Tekton Dashboard URL after your have completed the installation.  You can login to your OKD cluster and run ```oc get routes``` to find this or check in the OKD console.  This is useful for a few of the steps documented below.  You can find more details about the dashboard at https://github.com/tektoncd/dashboard.

NOTE: Everything is assumed to be running in `kabanero` namespace.  If you would like to deploy the application in a different namespace, please update the app-deploy.yaml to point to the namespace to deploy too.

### Create a persistent volume
The persistent volume is used by the pipelines.  An example pv definition is provided.  Update path and other values in pv.yaml to suit your requirements.

Login to your cluster.  For example for OKD,

```
oc login <master node IP>:8443
```

Clone the pv.yaml in this repo and apply it.

```
cd ./pipelines/common
oc apply -f pv.yaml -n kabanero
```

### Create secrets to pull from git repo and push to docker registry

This has to be created in the `kabanero` namespace and associated with the `kabanero-operator` service account.  The secrets can be created in a few different ways.  Simplest option is to go configure this is the Tekton Dashboard under the secrets section as given [here](https://github.com/tektoncd/experimental/blob/master/webhooks-extension/docs/GettingStarted.md#create-credentials-git).  
Alternatively you can configure this in the OKD console or you can setup the secret using the OKD CLI. 


## Execute pipelines using Tekton Dashboard Webhook Extension

You can leverage the Tekton Dashboard Webhook Extensions to drive the pipelines automatically by configuring webhooks to github.  This enables the CI/CD flow by automatically building and deploying the applications with code updates.  Events such as commits or pull requests in a github repo can be setup to automatically trigger pipeline runs.

For detailed description on creating a web hook to git, please visit these resources:
https://kabanero.io/docs/ref/general/tekton-webhooks.html
https://github.com/tektoncd/experimental/blob/master/webhooks-extension/docs/GettingStarted.md

## Manual pipeline execution using a script

If you are developing a new pipeline and would like to manually test it in a tight loop, using the script or manually driving pipelines might be more helpful than using a webhook.  Steps below describe how to do that.

Login to your cluster.  For example for OKD,

```
oc login <master node IP>:8443
```

### Clone the kabanero pipelines repo

```
git clone https://github.com/kabanero-io/kabanero-pipelines
```

### Run the script with the appropriate parameters
```
cd ./pipelines/incubator/manual-pipeline-runs/

./manual-pipeline-run-script.sh -r [git_repo of the Appsody project] -i [docker registery path of the image to be created] -c [collections name of which pipeline to be run]"
```

For example:
```
./manual-pipeline-run-script.sh -r https://github.com/mygitid/appsody-test-project -i index.docker.io/mydockeid/my-java-microprofile-image -c java-microprofile"
```

## Manual pipeline execution via CLI

Login to your cluster.  For example for OKD,

```
oc login <master node IP>:8443
```

### Clone the kabanero pipelines repo

```
git clone https://github.com/kabanero-io/kabanero-pipelines
cd kabanero-pipelines
```

### Create PipelineResources

Update the pipeline-resources.yaml with github & docker repo info to create the PipelineResources.  Sample pipeline-resources.yaml files are provided for each featured collection under the manual-pipeline-runs dir.  Update the docker-image URL.  You can use the sample github repo provided or update it to point to your github repo.

After updating the file, apply it

```
oc apply -f <collection-name>-pipeline-resources.yaml
```

### Activate the tasks & pipelines
The installations will activate the featured collections should have activated the tasks and pipelines already.  If you are creating a new task or pipeline, activate them manually

```
oc apply -f <task.yaml>
oc apply -f <pipeline.yaml>
```

### Run the pipeline

Sample PipelineRun files are provided under ./pipelines/manual-pipeline-runs.  Locate the appropriate pipeline-run file and execute it.
```
oc apply -f <collection-name>-pipeline-run.yaml
```

# Checking the status of the pipeline run

You can check the status of the pipeline run from the OKD console, command line, or Tekton dashboard.

### Command line:
```
oc get pipelineruns
oc -n kabanero describe pipelinerun.tekton.dev/<pipeline-run-name> 
```
You should also see pods for the pipeline runs that you can ```oc describe``` and ```oc logs``` to get more details of your run.

If the pipeline run was successful, you should see a docker image in your docker registry and you should see a pod that's running your application.

# Troubleshooting 

## My pipelinerun failed in Tekton Dashboard with `Unable to fetch log`, what is wrong?
   
  Throubleshooting steps
   - Check whether your pipelinerun failed due to `unbound PersistentVolumeClaims`
   
   Command:
   
   `kubectl get pipelineruns/pipelinerun-name -o yaml`
   
   Sample Output:
   
   ```
      lastTransitionTime: 2019-09-25T19:36:56Z
    message: Not all Tasks in the Pipeline have finished executing
    reason: Running
    status: Unknown
    type: Succeeded
    startTime: 2019-09-25T19:36:59Z
    taskRuns:
        kab-nodejs-express-wbh-2-1569440216-build-task-r8klh:
          pipelineTaskName: build-task
          status:
            conditions:
             lastTransitionTime: 2019-09-25T19:37:00Z
              message: "pod status "PodScheduled":"False"; message: "pod has unbound PersistentVolumeClaims
                (repeated 2 times)"
              reason: Pending
              status: Unknown
              type: Succeeded
            podName: kab-nodejs-express-wbh-2-1569440216-build-task-r8klh-pod-5172ba
            startTime: 2019-09-25T19:36:59Z
    [root@escapes1 common]# ls
   
   ```
   
   - If you see above message you have to check if persistent volume is applied for pipelinerun
   
    Command:
    `kubectl get PersistentVolume`
   
    Sample output:
   
     ```
     NAME                      CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                    STORAGECLASS   REASON    AGE
     manual-pipeline-run-pvc   5Gi        RWO            Recycle          Available                                                     1s
     registry-volume           10Gi       RWX            Retain           Bound       default/registry-claim                            13d
     ```
   
     NOTE: You should see two persistent volumes as shown above, `registry-volume` is by default present for you and `manual-pipeline-run-pvc` 
     is supposed to be applied as manual pre-requisite step before running any pipelinerun. Follow steps [here](https://github.com/kabanero-io/kabanero-pipelines/blob/master/README.md#create-a-persistent-volume)
    
## I see the error below while running the building step of a Kabanero Pipeline.The cause of this could be either of the 3 situations mentioned below before running the pipelines

    - The user has created a secret for github but not patched that secret onto the service account used by the PipelineRun or TaskRun in question, or
    - The user has not created a secret for github, but has tried to patch the relevant service account, or
    - The user has not created a secret for github and has not patched the relevant service account

Error Snippet:
{"level":"warn","ts":1568057939.538,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
{"level":"error","ts":1568057939.8545134,"logger":"fallback-logger","caller":"git/git.go:35","msg":"Error running git [fetch --depth=1 --recurse-submodules=yes origin fc7fe7fb8d87779dd5419b509dd2c91e63ba87b7]: exit status 128\nfatal: could not read Username for 'https://github.ibm.com': No such device or address\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\t/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:35\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\t/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:88\nmain.main\n\t/go/src/github.com/tektoncd/pipeline/cmd/git-init/main.go:36\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:198"}
{"level":"error","ts":1568057940.1771348,"logger":"fallback-logger","caller":"git/git.go:35","msg":"Error running git [pull --recurse-submodules=yes origin]: exit status 1\nfatal: could not read Username for 'https://github.ibm.com': No such device or address\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\t/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:35\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\t/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:91\nmain.main\n\t/go/src/github.com/tektoncd/pipeline/cmd/git-init/main.go:36\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:198"}
{"level":"warn","ts":1568057940.1772096,"logger":"fallback-logger","caller":"git/git.go:92","msg":"Failed to pull origin : exit status 1"}
{"level":"error","ts":1568057940.1798232,"logger":"fallback-logger","caller":"git/git.go:35","msg":"Error running git [checkout fc7fe7fb8d87779dd5419b509dd2c91e63ba87b7]: exit status 128\nfatal: reference is not a tree: fc7fe7fb8d87779dd5419b509dd2c91e63ba87b7\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\t/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:35\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\t/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:94\nmain.main\n\t/go/src/github.com/tektoncd/pipeline/cmd/git-init/main.go:36\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:198"}
{"level":"fatal","ts":1568057940.179904,"logger":"fallback-logger","caller":"git-init/main.go:37","msg":"Error fetching git repository: exit status 128","stacktrace":"main.main\n\t/go/src/github.com/tektoncd/pipeline/cmd/git-init/main.go:37\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:198"}

Step failed


 Throubleshooting steps
  - When running your Tekton Pipelines, if you see a `fatal: could not read Username for *GitHub  repository*: No such device or address` message in your failing Task logs, this indicates there is no `tekton.dev/git`  annotated GitHub secret in use by the ServiceAccount that launched this PipelineRun. You need to create one via the Tekton Dashboard. The annotation will be added and the specified ServiceAccount will be patched.

**Comment by mtamboli** [comment] 2019-10-11 02:24
@kvijai82 I looked at the doc above. I still do not understand a few things:
1. I am not able to follow directions for `Manual pipeline execution via CLI`. What CLI are we talking about here?
Are these steps for if you have updated pipelines as part of the collections?
![image](https://user-images.githubusercontent.com/29490950/66619378-b713b300-ebaa-11e9-8ba1-04e51d065430.png)

-  So if one has its own clone of collections, would it be running pipelines from the collection?

2. Pipelines are part of collection. So pipelines can be updated for a collections? Need documentation on how to update the pipeline for adding any tasks. kabanero-io/kabanero-pipelines#79

`Create a persistent volume` - only needed if the cluster does not have network storage configured.
Also, if you create PV, you also need to create mount directory? In the guide, it might be better to provide sample yaml file to apply for creating PV?

**Comment by kvijai82** [comment] 2019-10-11 13:44
@mtamboli thanks for the feedback!

On point 1, the CLI is just a set of oc commands to run the pipeline manually.  So if you writing a pipeline / task versus using it as part of your CI/CD workflow, I think this is the process a user might find easier to follow.  As part of Kabanero, we ship one pipeline that is used by all the collections.  When you build the collections, they get packaged into each collection type.  These are steps you could follow if you were tinkering with the pipeline in the collection and wanted to manually test it.

On point 2, users can add whatever pipelines / tasks they want to any collection.  There is nothing unique in Kabanero about it.  They would just follow Tekton docs to write a task and they can update the pipeline we ship or create a new one.  So I am not really sure what we should be documenting for https://github.com/kabanero-io/kabanero-pipelines/issues/79

For persistent volumes, we do have a sample pv.yaml in the pipelines repo.  I will update the doc to link to it.  I am trying to understand a few more things in this space and will update the PV portion of the doc next week once we get through a few more experiments and discussions we have planned.

Will make a few more tweaks and get your feedback later today.

**Comment by bschrammIBM** [comment] 2019-10-14 21:11
Add this step as a Troubleshooting option to the pipelines guide: (discussed on slack convo here: 
https://ibm-cloud.slack.com/archives/CKM8XAUE9/p1571077506124100)
Issue: The Tekton Pipeline Webhook returns the following error:
`Last Delivery was not successful.  Invalid HTTP response 503.`

Solution:
Redeliver the webhook.

**Comment by bschrammIBM** [comment] 2019-10-14 21:14
Another issue for the Pipelines Guide from slack convo here: https://ibm-cloud.slack.com/archives/CKM8XAUE9/p1571061948116600

The Tekton Dashboard may experience errors when accessed from Firefox ESR.

**Comment by dmuelle** [comment] 2019-10-15 17:57
Hi @kvijai82 - is the draft above ready for ID review, or are you still adding to it? Also, should this doc be a guide (like https://kabanero.io/guides/collection-springboot2/) ? Just rying to get an idea of what work is needed before Friday's 0.2 release

Thanks!

**Comment by kvijai82** [comment] 2019-10-16 10:31
@dmuelle yes this is ready for review.  I was initially thinking this would be a doc in the reference section of the website, but am open to making this a guide if folks think that would be more useful.  I created a PR in the kab pipelines repo to update the readme there with this contents in pasted as a comment above to make it easier to read:  https://github.com/kabanero-io/kabanero-pipelines/tree/Readme-updates-1

Please review and let me know what I should update.  Thanks.

**Comment by marikaj123** [comment] 2019-10-17 00:21
@mtamboli - From SVT perspective do you have what you need to test your scenario?

**Comment by marikaj123** [comment] 2019-10-17 00:23
According to @kvijai82 - looking to complete the work by this Friday.

**Comment by dmuelle** [comment] 2019-10-17 13:22
Working draft in progress at https://github.com/kabanero-io/draft-guide-working-with-pipelines

**Comment by dmuelle** [comment] 2019-10-17 19:19
Guide at https://github.com/kabanero-io/draft-guide-working-with-pipelines is ready for review

@ralanlittle @nateziemann

**Comment by marikaj123** [comment] 2019-10-17 20:23
Waiting for Nate and Alan to review and then close

**Comment by dmuelle** [comment] 2019-11-21 15:05
@aadeshpa & @kvijai82  are working on updates to address custom collections- I'll review and edit again when when they're done.

**Comment by mtamboli** [comment] 2019-11-21 15:35
I think this guide should be useful to Champ who is trying to to customize pipelines for its collections. I am running that scenario now and missing below information. Here are the pieces which are missing and are specific to how we build our Collections.

1. How do I customize pipelines so that they override common pipelines. You need a directory under specific collection. Should it be named default/common? Should it have collectionID prefix for name?

2. When adding a new pipeline or task at the common level, there are certain expectation which are unique to kabanero. For example CollectionID prefix is replaced later. What are those changes so that operator can work correctly. 

I have a correct Tekton task and pipeline which works on Openshift cluster but I need instructions to make correct updates to pipelines in collections so that kabanero operator can work correctly with new collection.

**Comment by dmuelle** [comment] 2019-11-21 17:58
@mtamboli I believe some of this is being addressed in @aadeshpa fork- see this PR

https://github.com/aadeshpa/draft-guide-working-with-pipelines/pull/1

**Comment by kvijai82** [comment] 2019-11-21 18:46
@mtamboli good points. I will try to update the guide with those.

**Comment by dmuelle** [comment] 2020-01-03 18:48
@marikaj123 @jantley-ibm we have incorporated @aadeshpa & @kvijai82 updates for this doc and it is awaiting final review in this PR

https://github.com/kabanero-io/draft-guide-working-with-pipelines/pull/13

**Comment by dmuelle** [comment] 2020-01-13 18:52
This doc has been reviewed by Alan and approved for publication via this PR

https://github.com/kabanero-io/draft-guide-working-with-pipelines/pull/13

**Comment by dmuelle** [comment] 2020-01-13 20:05
Hold off from publishing per @kvijai82 - changes coming next iteration that will make some of the info obsolete

**Comment by dmuelle** [comment] 2020-01-23 18:53
@kvijai82 says to go ahead and publish- we'll revise soon as changes come through

**Comment by alohr51** [comment] 2020-02-03 15:38
This was published awhile ago at https://kabanero.io/guides/pipelines-getting-started/

**Closed by alohr51** 2020-02-03 15:38 UTC
Labels: ID-reviewed, documentation-id, guide, ready-to-publish, svt
