### ISSUE TITLE
Add content to the What's New Doc - Ongoing work

### ISSUE THREAD

**Issue by alohr51** [kabanero-io/docs#49] opened 2019-08-15 19:46 UTC
We have a what's new doc that is tied to the website. It will notify website users only once whenever this file is updated with a new `version` in the front matter

Need this to be updated https://github.com/kabanero-io/docs/blob/master/ref/general/whats-new.md

**Comment by alohr51** [comment] 2019-08-15 21:39
@marikaj123 We'll need to find the right person to write this doc for each release.

**Comment by marikaj123** [comment] 2019-08-15 22:37
@bschrammIBM - Would the ID be under Brandy's team?

**Comment by marikaj123** [comment] 2019-10-02 22:22
@jantley-ibm - Does the issue contain what is needed for the ID team to provide the 'ID-reviewed' label?

**Comment by marikaj123** [comment] 2019-10-04 19:08
Ongoing work. the issue is a maintenance task needed for every release.

**Comment by marikaj123** [comment] 2019-10-17 20:21
According to Andrew, we can close it.

**Closed by marikaj123** 2019-10-17 20:22 UTC
Labels: documentation, release-0.2
